[
  {
    id: 1,
    title: "cake",
    description: "Syrian cake",
    img: require("../assets/cake.jpg"),
    tit: "sugher ",
    tit2: "eggs",
    nu1: 2,
    nu2: 3,
    klic: false,
  },
  {
    id: 2,
    title: "meat",
    description: "Syrian meat",
    img: require("../assets/meat.jpg"),
    tit: "proteen ",
    tit2: "chiken",
    nu1: 2,
    nu2: 3,
    klic: false,
  },
  {
    id: 3,
    title: "pizaa",
    description: "Syrian pizaa",
    img: require("../assets/pizaa.jpg"),
    tit: "tomato ",
    tit2: "salt",
    nu1: 2,
    nu2: 1,
    klic: false,
  },
  {
    id: 4,
    title: "vegitable",
    description: "Syrian vegitable",
    img: require("../assets/vege.jpg"),
    tit: "appel",
    tit2: "bananas",
    nu1: 4,
    nu2: 3,
    klic: false,
  },
  {
    id: 5,
    title: "cake",
    description: "Syrian cake",
    img: require("../assets/cake.jpg"),
    tit: "sugher",
    tit2: "eggs",
    nu1: 2,
    nu2: 3,
    klic: false,
  },
  {
    id: 6,
    title: "meat",
    description: "Syrian meat",
    img: require("../assets/meat.jpg"),
    tit: "proteen ",
    tit2: "chiken",
    nu1: 2,
    nu2: 3,
    klic: false,
  },
  {
    id: 7,
    title: "pizaa",
    description: "Syrian pizaa",
    img: require("../assets/pizaa.jpg"),
    tit: "tomato ",
    tit2: "salt",
    nu1: 2,
    nu2: 3,
    klic: false,
  },
  {
    id: 8,
    title: "vegitable",
    description: "Syrian vegitable",
    img: require("../assets/vege.jpg"),
    tit: "appel",
    tit2: "bananas",
    nu1: 2,
    nu2: 3,
    klic: false,
  },
];
